server.port: 7003
server.error.include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/review-db?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: '0000'

spring.jpa.hibernate.ddl-auto: update

logging:
  level:
    root: INFO
    com.microservices: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring.profiles: docker

server.port: 8080