server.port: 7003
server.error.include-message: always

spring.jpa.hibernate.ddl-auto: update

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/review-db?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: '0000'

spring.datasource.hikari.initializationFailTimeout: 60000

logging:
  level:
    root: INFO
    com.microservices: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring.profiles: docker

spring:
  datasource:
    url: jdbc:mysql://mysql/review-db?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true
    username: user
    password: 'pwd'
    validationQuery: SELECT 1

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create

server.port: 8080