version: '3'

services:
  product:
    build: microservices/product-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  recommendation:
    build: microservices/recommendation-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  review:
    build: microservices/review-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  product-composite:
    build: microservices/product-composite-service
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

#  mongodb:
#    image: mongo:latest
#    mem_limit: 350m
#    ports:
#      - "27017:27017"
#    command: mongod --smallfiles
#
#  mysql:
#    image: mysql:latest
#    mem_limit: 350m
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=0000
#      - MYSQL_DATABASE=review-db
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=0000
#    healthcheck:
#      test: [ "CMD", "mysqladmin" ,"ping", "-uuser", "-ppwd", "-h", "localhost" ]
#      interval: 10s
#      timeout: 5s
#      retries: 10